include pre-push husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,8 +5,8 @@ BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 PROTECTED_BRANCHES="^(main)"
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
-  echo -e "Can't push to remote $BRANCH branch, please create your own branch and use PR."
-  && exit 1
+  echo -e "Can't push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
 fi
+echo -e ">> Finish checking branch name"
 
 exit 0
