include can't push directly to main

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,12 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-branchName=$(git branch | grep '*' | sed 's/* //')
+branchName="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ $branchName == "master" ] then
-  echo "You can't commit directly to main branch"
-  exit 1
+if [ $branchName == "main" ]; then
+  echo "You can't commit directly to main branch" && exit 1
 fi
+echo -e ">> Finish checking branch name"
 
 npm run lint
 npm run test
