include local configuration for commit and push

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,14 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branchName=$(git branch | grep '*' | sed 's/* //')
+
+if [ $branchName == "master" ] then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
 npm run lint
 npm run test
+
+exit 0
